// ---------------------------------------------------------------------------------------------------
// generateIosStore — scaffolds the two plain-text iOS files for a store from its single source of
// truth (config/stores/<store>.properties via buildSrc/StoreManifest.kt):
//
//   1. iosApp/Configuration/Config-<store>.xcconfig
//   2. iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp-<store>.xcscheme
//
// The third piece — the Store<X>-Debug/Release build configurations inside project.pbxproj — is an
// Xcode-managed file and must still be added by hand (Xcode ▸ Project ▸ Info ▸ Configurations ▸
// duplicate). See docs/IOS_FLAVORS.md.
//
// Applied from the root build.gradle.kts.  Usage:  ./gradlew generateIosStore -Pstore=storeD
// ---------------------------------------------------------------------------------------------------
tasks.register("generateIosStore") {
    group = "ios"
    description = "Generate the iOS xcconfig + scheme for -Pstore=<store> from its .properties file."

    // Captured at configuration time so the task action stays configuration-cache compatible
    // (no Project access inside doLast).
    val storeProp = providers.gradleProperty("store")
    val projectRoot = rootDir

    doLast {
        val store = storeProp.orNull?.trim().orEmpty()
        require(store.isNotEmpty()) {
            "Pass the store, e.g.  ./gradlew generateIosStore -Pstore=storeD"
        }
        val known = StoreManifest.stores(projectRoot).keys
        require(store in known) {
            "Unknown store '$store'. Create config/stores/$store.properties first. Known stores: $known"
        }

        val features = StoreManifest.featuresFor(projectRoot, store)
        val appId = StoreManifest.applicationId(projectRoot, store)      // com.isharaw.kmpproj.<store>
        val configName = store.replaceFirstChar(Char::uppercase)     // storeD -> StoreD

        // A feature needs a flag only if it has a `#if STORE_HAS_X` guard in Swift. Today that's just
        // invoices — add feature names here as their Swift UI gains guards.
        val swiftGuardedFeatures = setOf("invoices")
        val swiftConditions = features
            .filter { it in swiftGuardedFeatures }
            .joinToString(" ") { "STORE_HAS_${it.uppercase()}" }

        // 1. xcconfig ---------------------------------------------------------------------------
        val xcconfig = projectRoot.resolve("iosApp/Configuration/Config-$store.xcconfig")
        xcconfig.writeText(
            """
            // $store configuration — GENERATED by ':generateIosStore' from config/stores/$store.properties.
            // Do not edit by hand; re-run the task instead.
            TEAM_ID=

            PRODUCT_NAME=KmpProj
            PRODUCT_BUNDLE_IDENTIFIER=$appId

            CURRENT_PROJECT_VERSION=1
            MARKETING_VERSION=1.0

            // Drives the Kotlin framework build phase (-Pstore=${'$'}GRADLE_STORE).
            GRADLE_STORE=$store
            // One STORE_HAS_<FEATURE> flag per shipped feature that has a Swift #if guard.
            SWIFT_ACTIVE_COMPILATION_CONDITIONS=$swiftConditions
            """.trimIndent() + "\n",
        )

        // 2. scheme -----------------------------------------------------------------------------
        val scheme = projectRoot.resolve("iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp-$store.xcscheme")
        scheme.parentFile.mkdirs()
        scheme.writeText(
            """
            <?xml version="1.0" encoding="UTF-8"?>
            <Scheme
               LastUpgradeVersion = "2600"
               version = "1.3">
               <BuildAction
                  parallelizeBuildables = "YES"
                  buildImplicitDependencies = "YES">
                  <BuildActionEntries>
                     <BuildActionEntry
                        buildForTesting = "YES"
                        buildForRunning = "YES"
                        buildForProfiling = "YES"
                        buildForArchiving = "YES"
                        buildForAnalyzing = "YES">
                        <BuildableReference
                           BuildableIdentifier = "primary"
                           BlueprintIdentifier = "07488F9A9FA4A7D59E69DE7B"
                           BuildableName = "KmpProj.app"
                           BlueprintName = "iosApp"
                           ReferencedContainer = "container:iosApp.xcodeproj">
                        </BuildableReference>
                     </BuildActionEntry>
                  </BuildActionEntries>
               </BuildAction>
               <TestAction
                  buildConfiguration = "$configName-Debug"
                  selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
                  selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
                  shouldUseLaunchSchemeArgsEnv = "YES">
                  <Testables>
                  </Testables>
               </TestAction>
               <LaunchAction
                  buildConfiguration = "$configName-Debug"
                  selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
                  selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
                  launchStyle = "0"
                  useCustomWorkingDirectory = "NO"
                  ignoresPersistentStateOnLaunch = "NO"
                  debugDocumentVersioning = "YES"
                  debugServiceExtension = "internal"
                  allowLocationSimulation = "YES">
                  <BuildableProductRunnable
                     runnableDebuggingMode = "0">
                     <BuildableReference
                        BuildableIdentifier = "primary"
                        BlueprintIdentifier = "07488F9A9FA4A7D59E69DE7B"
                        BuildableName = "KmpProj.app"
                        BlueprintName = "iosApp"
                        ReferencedContainer = "container:iosApp.xcodeproj">
                     </BuildableReference>
                  </BuildableProductRunnable>
               </LaunchAction>
               <ProfileAction
                  buildConfiguration = "$configName-Release"
                  shouldUseLaunchSchemeArgsEnv = "YES"
                  savedToolIdentifier = ""
                  useCustomWorkingDirectory = "NO"
                  debugDocumentVersioning = "YES">
                  <BuildableProductRunnable
                     runnableDebuggingMode = "0">
                     <BuildableReference
                        BuildableIdentifier = "primary"
                        BlueprintIdentifier = "07488F9A9FA4A7D59E69DE7B"
                        BuildableName = "KmpProj.app"
                        BlueprintName = "iosApp"
                        ReferencedContainer = "container:iosApp.xcodeproj">
                     </BuildableReference>
                  </BuildableProductRunnable>
               </ProfileAction>
               <AnalyzeAction
                  buildConfiguration = "$configName-Debug">
               </AnalyzeAction>
               <ArchiveAction
                  buildConfiguration = "$configName-Release"
                  revealArchiveInOrganizer = "YES">
               </ArchiveAction>
            </Scheme>
            """.trimIndent() + "\n",
        )

        logger.lifecycle("Generated iOS store '$store':")
        logger.lifecycle("  ${xcconfig.relativeTo(projectRoot)}")
        logger.lifecycle("  ${scheme.relativeTo(projectRoot)}")
        logger.lifecycle("")
        logger.lifecycle("Remaining manual step (Xcode): add the $configName-Debug / $configName-Release")
        logger.lifecycle("build configurations (Project ▸ Info ▸ Configurations ▸ duplicate), then pick the")
        logger.lifecycle("iosApp-$store scheme. See docs/IOS_FLAVORS.md §Step 4.")
    }
}
